// Generated by fintools/sync-wrappers.mjs. Do not edit directly.

/**
 * Taken settlement dates, maturity dates and yields, produce an NSS fitted yield curve.
 * This is a wrapper around the code I pulled from the KevinM (aerokam) yield curves
 * for TIPS. He likely adapted it from somewhere else too (Claude?).
 *
 * XXXX - consider parameterizing SAO smoothing boundaries. May be useful after forward efforts are settled.
 *
 * Send the following to the SAO calculation:
 * bonds[] include
 * bonds.settlementDate
 * bonds.maturityDate
 * bonds.saYield
 * bonds.yrs
 *
 * @param {Date[]} settles settlement dates
 * @param {Date} matures maturity dates
 * @param {number[]} yields seasonally adjusted yields
 * @param {boolean} shortEndTweak [OPTIONAL, default = TRUE] hold the curve flat below its shortest fitted maturity.
 * @return {number[][]}
 * @customfunction
 */
function getSaoCurve(settles, matures, yields, shortEndTweak = true) {
  return fintools.getSaoCurve(settles, matures, yields, shortEndTweak);
}
