// Generated by fintools/sync-wrappers.mjs. Do not edit directly.

/**
 * Returns a TSP fund's share price from TSPtalk.com, using the script cache.
 * No header. Example: =TSPGetCachedPrice("F")
 * @param {string} fundLetter Required fund letter: G, F, C, S, or I.
 * @param {boolean} [forceRefresh=false] Bypass the cached quote.
 * @return {Array<Array<Date|number>>} One row: [[asOfDate, price]]. Throws for invalid data.
 * @customfunction
 */
function TSPGetCachedPrice(fundLetter, forceRefresh = false) {
  return fintools.TSPGetCachedPrice(fundLetter, forceRefresh);
}
