// Generated by fintools/sync-wrappers.mjs. Do not edit directly.

/**
 * Returns multpl.com's latest S&P 500 CAPE (a dimensionless ratio), using the script cache.
 * Source: https://www.multpl.com/shiller-pe/table/by-month
 * No header. Retrieval failures propagate. Example: =multplGetCachedCAPE()
 * @param {boolean} [forceRefresh=false] Bypass the cached result.
 * @return {Array<Array<Date|number>>} One row: [[reportDate, CAPE]].
 * @customfunction
 */
function multplGetCachedCAPE(forceRefresh = false) {
  return fintools.multplGetCachedCAPE(forceRefresh);
}
