// Generated by fintools/sync-wrappers.mjs. Do not edit directly.

/**
 * Returns Yahoo's market price (stocks/ETFs) or NAV (mutual funds), without a header.
 * Uses the document cache when available, otherwise the script cache.
 * Date preserves the source epoch instant; Sheets controls its displayed timezone.
 * Change is a decimal (0.01 = 1%), or "" if previous close is unavailable.
 * Throws for missing/invalid quote data. Example: =yahooGetCachedPrice("VTI", TRUE)
 * @param {string} ticker Yahoo ticker.
 * @param {boolean} [includeChangePct=false] Include the third column.
 * @param {boolean} [forceRefresh=false] Bypass the cached quote.
 * @return {Array<Array<Date|number|string>>} [[asOf, price]] or [[asOf, price, change]].
 * @customfunction
 */
function yahooGetCachedPrice(ticker, includeChangePct = false, forceRefresh = false) {
  return fintools.yahooGetCachedPrice(ticker, includeChangePct, forceRefresh);
}

/**
 * Returns Yahoo's fund expense ratio as a decimal (0.0003 = 0.03%), using the user cache.
 * Missing/not-applicable expense ratios return "n/a"; malformed values throw.
 * Example: =yahooGetCachedExpenseRatio("VTI")
 * @param {string} ticker Fund ticker.
 * @param {boolean} [forceRefresh=false] Bypass the cached result.
 * @return {number|string} Scalar decimal ratio or "n/a", not an array.
 * @customfunction
 */
function yahooGetCachedExpenseRatio(ticker, forceRefresh = false) {
  return fintools.yahooGetCachedExpenseRatio(ticker, forceRefresh);
}
