// Generated by fintools/sync-wrappers.mjs. Do not edit directly.

/**
 * Returns the active sheet's name, not necessarily the sheet containing a formula.
 * Renaming or selecting a sheet is not a formula dependency; re-enter the formula to refresh.
 * Example: =ssGetSheetName()
 * @return {string} Active sheet name.
 * @customfunction
 */
function ssGetSheetName() {
  return fintools.ssGetSheetName();
}

/**
 * Returns the top-left cell value of a named range. Throws if the range is not found.
 * Prefer direct named-range references in formulas so Sheets tracks dependencies.
 * Example (script): ssGetNamedRangeValue("TitleRange")
 * @param {string} namedRange Name, matched after any sheet-name prefix.
 * @return {string|number|boolean|Date} Top-left cell value.
 * @customfunction
 */
function ssGetNamedRangeValue(namedRange) {
  return fintools.ssGetNamedRangeValue(namedRange);
}

/**
 * Sets a named range's cell value(s). Script/menu use only; not a worksheet custom function.
 * Throws if the range is not found. Example (script): ssSetNamedRangeValue("TitleRange", "Title")
 * @param {string} namedRange Name, matched after any sheet-name prefix.
 * @param {string|number|boolean|Date} value Value applied to the range.
 * @return {string} Empty string on success.
 */
function ssSetNamedRangeValue(namedRange, value) {
  return fintools.ssSetNamedRangeValue(namedRange, value);
}

/**
 * Finds exact named-range tokens in formulas in a sheet's used range.
 * Ignores quoted strings/sheet names, function names, and longer identifiers.
 * This is lexical matching, not a formula parser; INDIRECT strings are not references.
 * Example: =ssTrackRangeUses("Sheet1", "MyRange")
 * @param {string} sheetName Sheet to search.
 * @param {string} namedRange Named-range token to match.
 * @return {Array<Array<string>>|string} A1 references in row order, one per row; "" if none.
 * @customfunction
 */
function ssTrackRangeUses(sheetName, namedRange) {
  return fintools.ssTrackRangeUses(sheetName, namedRange);
}
