// Generated by fintools/sync-wrappers.mjs. Do not edit directly.

/**
 * Calculates the forward clean price of a nominal Treasury
 * note or bond.
 *
 * Carries the dirty value from settlement (t0) to the
 * forward date (t1), while removing coupons paid between
 * settlement and the forward date.
 *
 * Unlike the TIPS version, there is no inflation/index-ratio
 * conversion. All values are already nominal dollars per
 * $100 face value.
 *
 * Coupons occurring ON the forward date are treated as
 * belonging to the original holder and are therefore removed.
 * The resulting forward bond value is ex-coupon on that date.
 *
 * A clean price above $100 is completely valid and requires
 * no special treatment.
 *
 * Forward pricing relationship:
 *
 *   DirtyForward =
 *       DirtySpot * Carry(t0,t1)
 *       - Sum[Coupon * Carry(couponDate,t1)]
 *
 * Then:
 *
 *   CleanForward =
 *       DirtyForward
 *       - AccruedInterest(t1)
 *
 * @param {Date} settle Current settlement date (t0)
 * @param {Date} forward Forward settlement date (t1)
 * @param {Date} maturity Maturity date
 * @param {number} coupon Annual nominal coupon rate (decimal)
 * @param {number} price Current quoted nominal clean price
 * @param {number} repoRate Repo/T-bill financing rate (decimal)
 *
 * @return {number|string} Forward quoted nominal clean price
 * @customfunction
 */
function mybondCalcNominalForwardCP(settle, forward, maturity, coupon, price, repoRate) {
  return fintools.mybondCalcNominalForwardCP(settle, forward, maturity, coupon, price, repoRate);
}
