// Generated by fintools/sync-wrappers.mjs. Do not edit directly.

/**
 * Calculates the forward clean price of a TIPS.
 *
 * Carries the nominal/indexed dirty value from settlement (t0)
 * to the forward date (t1), while removing any coupons paid
 * between settlement and the forward date.
 *
 * Each intervening coupon is valued using its coupon-date
 * index ratio and carried from its payment date to the
 * forward date. (TIPS case, at most 1 coupon is expected though)
 *
 * Note: Intervening coupons are defined as coupon dates strictly before
 * the forward date. A coupon occurring exactly on the forward date is
 * therefore not removed. In the intended TIPS application this boundary
 * case does not arise because coupon dates are on the 15th while forward
 * dates are on the 1st.
 *
 * @param {Date} settle Current settlement date (t0)
 * @param {Date} forward Forward settlement date (t1)
 * @param {Date} maturity Maturity date (t2)
 * @param {number} coupon Annual real coupon rate (decimal)
 * @param {number} price Current quoted real clean price
 * @param {number} datedRefCpi TIPS dated-date REFCPI
 * @param {number} settleRefCpi Settlement-date REFCPI
 * @param {number} forwardRefCpi Forward-date REFCPI
 * @param {number} repoRate Repo/T-bill financing rate (decimal)
 *
 * @return {number|string} Forward quoted real clean price
 * @customfunction
 */
function mybondCalcForwardCP(settle, forward, maturity, coupon, price, datedRefCpi, settleRefCpi, forwardRefCpi, repoRate) {
  return fintools.mybondCalcForwardCP(settle, forward, maturity, coupon, price, datedRefCpi, settleRefCpi, forwardRefCpi, repoRate);
}
