// Generated by fintools/sync-wrappers.mjs. Do not edit directly.

/**
 * Simple Canty Yield
 * See: https://www.risk.net/sites/default/files/import_unmanaged/risk.net/data/risk/pdf/technical/2009/risk_0109_technical_inflation.pdf
 * Implements formula 13, including the adjustment for real accrued interest.
 * Formula 14 omits the rai adjustment and is the more common implementation.
 *
 * @param {Date} settle Settlement date
 * @param {Date} maturity Maturity date
 * @param {number} coupon Annual coupon rate (decimal)
 * @param {number} price Real Clean Price
 * @param {number} settleFactor Seasonal Adjustment for Settlement date
 * @param {number} matureFactor Seasonal Adjustment for Maturity Date
 *
 * @return {number}
 * @customfunction
 */
function mybondSimpleCanty(settle, maturity, coupon, price, settleFactor, matureFactor) {
  return fintools.mybondSimpleCanty(settle, maturity, coupon, price, settleFactor, matureFactor);
}

/**
 * Simple Canty Price - the guts of SACP calculation using Canty formula (13)
 *
 * @param {Date} settle Settlement date
 * @param {Date} maturity Maturity date
 * @param {number} coupon Annual coupon rate (decimal)
 * @param {number} price Real Clean Price
 * @param {number} settleFactor Seasonal Adjustment for Settlement date
 * @param {number} matureFactor Seasonal Adjustment for Maturity Date
 *
 * @return {number}
 * @customfunction
 */
function mybondSimpleCantyPrice(settle, maturity, coupon, price, settleFactor, matureFactor) {
  return fintools.mybondSimpleCantyPrice(settle, maturity, coupon, price, settleFactor, matureFactor);
}

/**
 * Full Canty Yield - weights seasonal adjustments based upon each coupon's month.
 * See: https://www.risk.net/sites/default/files/import_unmanaged/risk.net/data/risk/pdf/technical/2009/risk_0109_technical_inflation.pdf
 * Implements Canty formula (17), including the adjustment for real accrued interest shown in formula 13.
 * Formula 14 omits the rai adjustment and is the more common implementation.
 *
 * @param {Date} settle Settlement date
 * @param {Date} maturity Maturity date
 * @param {number} coupon Annual coupon rate (decimal)
 * @param {number} price Real Clean Price
 * @param {number} settleFactor Seasonal Adjustment for Settlement date
 * @param {number} firstCouponFactor Seasonal Adjustment for 1st coupon (not maturity) date
 * @param {number} matureFactor Seasonal Adjustment for Maturity Date
 *
 * @return {number}
 * @customfunction
 */
function mybondFullCanty(settle, maturity, coupon, price, settleFactor, firstCouponFactor, matureFactor) {
  return fintools.mybondFullCanty(settle, maturity, coupon, price, settleFactor, firstCouponFactor, matureFactor);
}

/**
 * Full Canty Price - returns an seasonally adjusted Clean Price using Canty formual (17).
 *
 * @param {Date} settle Settlement date
 * @param {Date} maturity Maturity date
 * @param {number} coupon Annual coupon rate (decimal)
 * @param {number} price Real Clean Price
 * @param {number} settleFactor Seasonal Adjustment for Settlement date
 * @param {number} firstCouponFactor Seasonal Adjustment for 1st coupon (not maturity) date
 * @param {number} matureFactor Seasonal Adjustment for Maturity Date
 *
 * @return {number}
 * @customfunction
 */
function mybondFullCantyPrice(settle, maturity, coupon, price, settleFactor, firstCouponFactor, matureFactor) {
  return fintools.mybondFullCantyPrice(settle, maturity, coupon, price, settleFactor, firstCouponFactor, matureFactor);
}
