// Generated by fintools/sync-wrappers.mjs. Do not edit directly.

/**
 * Calculates the nominal treasury bill/note/bond yield to maturity for a cash flow starting at the settlement date
 * Uses an Google app script (javascript) XIRR implementation.
 * Years are calculated on a strict 365 day fraction consistent with my understanding of XIRR conventions.
 * Purchased accrued interest is negative coupon attribution at settlement;
 * later coupons are reported in full, with cumulative coupons net of that purchase.
 *
 * @param {Date} settle settlement date
 * @param {Date} maturity Maturity date
 * @param {number} coupon Annual coupon rate (decimal)
 * @param {number} settleCP settle real Clean Price
 *
 * @return {number} yield
 * @customfunction
 */
function mybondTreasuryReturn(settle, maturity, coupon, settleCP) {
  return fintools.mybondTreasuryReturn(settle, maturity, coupon, settleCP);
}

/**
 * Returns a table for graphing the nominal treasury bill/note/bond yield to maturity for a cash flow starting at the settlement date
 * Uses an Google app script (javascript) XIRR implementation model.
 * 1st row is the YTM calculated for this treasury.
 * 2nd row is the XIRR rate, and total coupons and discount.
 * 3rd row contains column header names.
 * 4th row onward is the graphing table. 1st two columns can be provided to xirr for a rate calculation (results provided in 1st row).
 * Years are calculated on a strict 365 day fraction consistent with my understanding of XIRR conventions.
 *
 * @param {Date} settle settlement date (t0)
 * @param {Date} maturity Maturity date (t2)
 * @param {number} coupon Annual coupon rate (decimal)
 * @param {number} settleCP settle Clean Price
 *
 * @return {[["irr/totals",xirrRate,cumCoupon,cumDiscount],[...header row...],[date,cashflow,cumCoupon,cumDiscount,currCoupon,currDiscount]]} table
 * @customfunction
 */
function mybondGraphTreasuryReturn(settle, maturity, coupon, settleCP) {
  return fintools.mybondGraphTreasuryReturn(settle, maturity, coupon, settleCP);
}
