// Generated by fintools/sync-wrappers.mjs. Do not edit directly.

/**
 * Calculates a quoted TIPS clean price from an annual-effective XIRR
 * and projected nominal (inflation-adjusted) TIPS cash flows.
 *
 * This is intended as the inverse of xirr_():
 *
 *     nominal cash flows -> XIRR
 *     XIRR + same cash flows -> nominal PV
 *
 * The nominal PV is then converted back to the quoted real TIPS
 * price using the settlement index ratio.
 *
 * cashFlows format:
 * [
 *   [date, cashflow, cumCoupon, cumDiscount, currCoupon, currDiscount],
 *   ...
 * ]
 *
 * @param {Date} settle Settlement date
 * @param {Date} maturity Maturity date
 * @param {number} coupon Annual real coupon rate (decimal)
 * @param {number} yld Annual-effective XIRR (decimal)
 * @param {number} settleIR Index ratio at settlement
 * @param {Array[]} cashFlows Nominal/inflation-adjusted future cash flows
 *
 * @return {number} Quoted real clean price
 * @customfunction
 */
function mytipsPriceFromXirr(settle, maturity, coupon, yld, settleIR, cashFlows) {
  return fintools.mytipsPriceFromXirr(settle, maturity, coupon, yld, settleIR, cashFlows);
}
