// Generated by fintools/sync-wrappers.mjs. Do not edit directly.

/**
* Robust XIRR implementation for Google Apps Script. Handles dates from sheets reasonably well.
* returns annualized effective yield (internal rate of return), not a bond equivalent yield.
*
* Uses in order:
*   1. Newton-Raphson (fast)
*   2. Binary Search fallback (robust)
*
* Returns annual effective yield.
*
* @param {number[]} cashFlows
* @param {Date[]} dates
* @param {number} guess OPTIONAL. default = 0.05, decimal guess at yield to seed the solver.
* @returns {number}
* @customfunction
*/
function mybondXIRR(cashFlows, dates, guess = 0.05) {
  return fintools.mybondXIRR(cashFlows, dates, guess);
}
