// Generated by fintools/sync-wrappers.mjs. Do not edit directly.

/**
 * Calculates the nominal yield of a TIPS to maturity for a cash flow starting at the settlement date
 * using a trend inflation assumption based upon a
 * known forward date and inflation to the forward date (max REFCPI).
 * Uses an Google app script (javascript) XIRR implementation.
 * This retrieves an unadjusted Trend Inflation rate.
 * Years are calculated on a strict 365 day fraction consistent with my understanding of XIRR conventions.
 *
 * @param {Date} settle settlement date
 * @param {Date} forward fwd (max REFCPI) date
 * @param {Date} maturity Maturity date
 * @param {number} coupon Annual coupon rate (decimal)
 * @param {number} settleRealCP settle real Clean Price
 * @param {number} forwardRealCP forward date real Clean Price; can be obtained by mybondCalcForwardCP()
 * @param {number} datedREFCPI dated date REFCPI
 * @param {number} settleREFCPI settlement date REFCPI
 * @param {number} forwardREFCPI date REFCPI on forward date
 * @param {number} inflator trend inflation rate (decimal)
 *
 * @return {number} yield
 * @customfunction
 */
function mybondTipsNominalReturnFromTrendInflation(settle, forward, maturity, coupon, settleRealCP, forwardRealCP, datedREFCPI, settleREFCPI, forwardREFCPI, inflator) {
  return fintools.mybondTipsNominalReturnFromTrendInflation(settle, forward, maturity, coupon, settleRealCP, forwardRealCP, datedREFCPI, settleREFCPI, forwardREFCPI, inflator);
}

/**
 * Calculates the nominal yield of a TIPS to maturity for a cash flow starting at the settlement date
 * using a trend inflation assumption based upon a
 * known forward date and inflation to the forward date (max REFCPI).
 * Uses an Google app script (javascript) XIRR implementation
 * This retrieves a Seasonally Adjusted Trend Inflation rate if seasonal is set to true.
 *
 * Seasonal Factors are applied to all cash flows that occur AFTER the forward date using the factor for the date
 * of the cashflow. the initial purchase and any coupons and inflation adjustments before the forward date are not
 * adjusted. All inflation and coupons AFTER forward date are adjusted including redemption.
 *
 * Years are calculated on a strict 365 day fraction consistent with my understanding of XIRR conventions.
 *
 * @param {Date} settle settlement date (t0)
 * @param {Date} forward fwd (max REFCPI) date (t1)
 * @param {Date} maturity Maturity date (t2)
 * @param {number} coupon Annual coupon rate (decimal)
 * @param {number} settleRealCP settle real Clean Price (t0)
 * @param {number} forwardRealCP forward date (t1) real Clean Price; can be obtained by mybondCalcForwardCP()
 * @param {number} datedREFCPI dated date REFCPI
 * @param {number} settleREFCPI settlement date REFCPI
 * @param {number} forwardREFCPI date REFCPI on forward date
 * @param {number} inflator trend inflation rate (decimal)
 * @param {boolean} seasonal [default = false] include seasonal adjustments if true, otherwise straight trend inflation.
 *
 * @return {number} yield
 * @customfunction
 */
function mybondTipsNominalReturn(settle, forward, maturity, coupon, settleRealCP, forwardRealCP, datedREFCPI, settleREFCPI, forwardREFCPI, inflator, seasonal = false) {
  return fintools.mybondTipsNominalReturn(settle, forward, maturity, coupon, settleRealCP, forwardRealCP, datedREFCPI, settleREFCPI, forwardREFCPI, inflator, seasonal);
}

/**
 * Returns a table for graphing the nominal TIPS yield to maturity for a cash flow starting at the settlement date
 * using a trend inflation assumption based upon a
 * known forward date and inflation to the forward date (max REFCPI).
 * This retrieves a Seasonally Adjusted Trend Inflation rate if seasonal is set to true.
 * Years are calculated on a strict 365 day fraction consistent with my understanding of XIRR conventions.
 * Uses an Google app script (javascript) XIRR implementation model.
 * 1st two columns can be provided to xirr for a rate calculation.
 *
 * @param {Date} settle settlement date (t0)
 * @param {Date} forward fwd (max REFCPI) date (t1)
 * @param {Date} maturity Maturity date (t2)
 * @param {number} coupon Annual coupon rate (decimal)
 * @param {number} settleRealCP settle real Clean Price (t0)
 * @param {number} forwardRealCP forward date (t1) real Clean Price; can be obtained by mybondCalcForwardCP()
 * @param {number} datedREFCPI dated date REFCPI
 * @param {number} settleREFCPI settlement date REFCPI (t0)
 * @param {number} forwardREFCPI date REFCPI on forward date (t1)
 * @param {number} inflator trend inflation rate (decimal) (from t1 to t2)
 * @param {boolean} seasonal [default = false] include seasonal adjustments if true, otherwise straight trend inflation.
 *
 * @return {[[date,cashflow,cumCouponReturn,cumDiscountReturn,currCoupon,currDiscountReturn]]} yield
 * @customfunction
 */
function mybondGraphTipsNominalReturn(settle, forward, maturity, coupon, settleRealCP, forwardRealCP, datedREFCPI, settleREFCPI, forwardREFCPI, inflator, seasonal = false) {
  return fintools.mybondGraphTipsNominalReturn(settle, forward, maturity, coupon, settleRealCP, forwardRealCP, datedREFCPI, settleREFCPI, forwardREFCPI, inflator, seasonal);
}
