// Generated by fintools/sync-wrappers.mjs. Do not edit directly.

/**
 * Calculates a simple annualized rate for a target date using
 * two Treasury bill prices.
 *
 * Normally:
 *   1. Convert each T-bill price to a discount factor.
 *   2. Log-linearly interpolate discount factors to the target date.
 *   3. Convert the target discount factor to a simple annualized rate.
 *
 * If both T-bills have the same maturity date:
 *   - The target must equal that maturity date.
 *   - Calculate the simple rate implied by each bill.
 *   - Return the arithmetic average of those two rates.
 *
 * T-bill prices are expressed per $100 maturity value.
 *
 * Simple-rate convention:
 *
 *   1 / DF = 1 + r * days / yearDays
 *
 * therefore:
 *
 *   r = (1 / DF - 1) * yearDays / days
 *
 * @param {Date} settle Settlement date
 * @param {Date} target Target/forward date
 * @param {Date} maturity1 First T-bill maturity
 * @param {number} price1 First T-bill price per $100 face
 * @param {Date} maturity2 Second T-bill maturity
 * @param {number} price2 Second T-bill price per $100 face
 *
 * @return {number} Simple annualized rate as a decimal
 * @customfunction
 */
function myTbillSimpleRate(settle, target, maturity1, price1, maturity2, price2) {
  return fintools.myTbillSimpleRate(settle, target, maturity1, price1, maturity2, price2);
}
