// Generated by fintools/sync-wrappers.mjs. Do not edit directly.

/**
 * Calculate the SA Factor for date. If the date provided is before the max REFCPI date,
 * return the BLS defined ratio. If after the max REFCPI, then lookup the most recent month/day reported and use that value.
 *
 * @param {Date} searchDate date
 *
 * @return {number}
 * @customfunction
 */
function tipsGetFactor(searchDate) {
  return fintools.tipsGetFactor(searchDate);
}

/**
 * Return that reported REFCPI for date. If the date provided is before the max REFCPI date,
 * return the BLS defined ratio. If after the max REFCPI, then return null.
 * This always reports the BLS NSA CPI value (not seasonally adjusted).
 * This may have a limited history to improve performance so dated date REFCPI may not be found here.
 *
 * @param {Date} searchDate date
 *
 * @return {number}
 * @customfunction
 */
function tipsGetRefCpi(searchDate) {
  return fintools.tipsGetRefCpi(searchDate);
}

/**
 * Return the maximum REFCPI date in the cached table as YYYY-MM-DD text.
 *
 * @return {string} Date only, without a time or timezone.
 * @customfunction
 */
function tipsGetMaxRefCpiDate() {
  return fintools.tipsGetMaxRefCpiDate();
}
