// Generated by fintools/sync-wrappers.mjs. Do not edit directly.

/**
 * Returns REFCPI.csv as a worksheet table with a header row and six columns.
 * Dates are returned as Date values; CPI values and factors are numbers.
 * @param {boolean} forceRefresh [OPTIONAL, default = FALSE]. true forces a new table, not use any available cache.
 * @return {Array<Array<Date|number|string>>} Date, REFCPINSA, REFCPISA, SAFactor, MMDD, maxREFCPI.
 * @customfunction
 */
function tipsGetCachedREFCPI(forceRefresh = false) {
  return fintools.tipsGetCachedREFCPI(forceRefresh);
}
