// Generated by fintools/sync-wrappers.mjs. Do not edit directly.

/**
 * Returns the latest bank APY from Cash Optimizer, using the script cache.
 * No header. APY is a decimal (0.04 = 4%). Throws for an unknown account or missing rate.
 * Example: =bankGetCachedRate("Ally", "Savings")
 * @param {string} bank Bank source name; see bankCachedAvailableBanks.
 * @param {string} account Account type, matched case-insensitively.
 * @param {boolean} [forceRefresh=false] Bypass the cached result.
 * @return {Array<Array<Date|number>>} One row: [[asOfDate, APY]].
 * @customfunction
 */
function bankGetCachedRate(bank, account, forceRefresh = false) {
  return fintools.bankGetCachedRate(bank, account, forceRefresh);
}

/**
 * Returns nonzero account APYs from Cash Optimizer, sorted by account type.
 * Uses the script cache; no header. APYs are decimals (0.04 = 4%).
 * Example: =bankGetCachedAllRates("Ally")
 * @param {string} bank Bank source name.
 * @param {boolean} [forceRefresh=false] Bypass the cached result.
 * @return {Array<Array<string|Date|number>>} Rows: [accountType, asOfDate, APY].
 * @customfunction
 */
function bankGetCachedAllRates(bank, forceRefresh = false) {
  return fintools.bankGetCachedAllRates(bank, forceRefresh);
}

/**
 * Compatibility alias for bankGetCachedAccountTypes; retains the original misspelling.
 * @param {string} bank Bank source name.
 * @param {boolean} [forceRefresh=false] Bypass the cached result.
 * @return {Array<string>} Sorted account types with positive APYs; no header.
 * @customfunction
 */
function bankGetCachedAccounTypes(bank, forceRefresh = false) {
  return fintools.bankGetCachedAccounTypes(bank, forceRefresh);
}

/**
 * Returns account types with positive APYs from Cash Optimizer, using the script cache.
 * Example: =bankGetCachedAccountTypes("Ally")
 * @param {string} bank Bank source name.
 * @param {boolean} [forceRefresh=false] Bypass the cached result.
 * @return {Array<string>} Sorted account types; no header.
 * @customfunction
 */
function bankGetCachedAccountTypes(bank, forceRefresh = false) {
  return fintools.bankGetCachedAccountTypes(bank, forceRefresh);
}

/**
 * Fetches raw Cash Optimizer bank-rate JSON text, without caching.
 * Entries contain accountType, asOfDate, and decimal apy. Throws on retrieval failure.
 * Example: =bankGetCurrentRateFileContents("Ally")
 * @param {string} bank Bank source name.
 * @return {string} JSON text, not parsed objects.
 * @customfunction
 */
function bankGetCurrentRateFileContents(bank) {
  return fintools.bankGetCurrentRateFileContents(bank);
}

/**
 * Returns Cash Optimizer bank APY history in ascending date order, using the script cache.
 * No header; APYs are decimals (0.04 = 4%). Throws when no matching history exists.
 * Example: =bankGetCachedRateHistory("Ally", "Savings", DATE(2026,1,1), DATE(2026,10,10))
 * @param {string} bank Bank source name.
 * @param {string} account Exact account type.
 * @param {Date|string} start_date Inclusive first date.
 * @param {Date|string} end_date Inclusive last date.
 * @param {boolean} [forceRefresh=false] Bypass the cached result.
 * @return {Array<Array<Date|number>>} Rows: [asOfDate, APY].
 * @customfunction
 */
function bankGetCachedRateHistory(bank, account, start_date, end_date, forceRefresh = false) {
  return fintools.bankGetCachedRateHistory(bank, account, start_date, end_date, forceRefresh);
}

/**
 * Returns the available Cash Optimizer APY history date range, using the script cache.
 * Throws for an unknown bank/account pair. No header.
 * Example: =bankGetCachedRateHistoryDates("Ally", "Savings")
 * @param {string} bank Bank source name.
 * @param {string} account Exact account type.
 * @param {boolean} [forceRefresh=false] Bypass the cached result.
 * @return {Array<Array<Date>>} One row: [[oldestDate, newestDate]].
 * @customfunction
 */
function bankGetCachedRateHistoryDates(bank, account, forceRefresh = false) {
  return fintools.bankGetCachedRateHistoryDates(bank, account, forceRefresh);
}

/**
 * Fetches raw Cash Optimizer bank/account APY history JSON without caching.
 * Entries contain accountType, asOfDate, and decimal apy. Tries legacy paths if needed.
 * Example: =bankGetCurrentRateHistoryFileContents("Ally", "Savings")
 * @param {string} bank Bank source name.
 * @param {string} account Required account type.
 * @return {string} JSON text, not parsed objects. Throws if all retrieval attempts fail.
 * @customfunction
 */
function bankGetCurrentRateHistoryFileContents(bank, account) {
  return fintools.bankGetCurrentRateHistoryFileContents(bank, account);
}

/**
 * Returns available bank source names from Cash Optimizer's Banks/bank-list.txt.
 * Uses the script cache. The source is a newline-separated list, not fund history.
 * Example: =bankCachedAvailableBanks()
 * @param {boolean} [forceRefresh=false] Bypass the cached result.
 * @return {Array<Array<string>>} One bank name per row; no header.
 * @customfunction
 */
function bankCachedAvailableBanks(forceRefresh = false) {
  return fintools.bankCachedAvailableBanks(forceRefresh);
}
